import Image from 'next/image'
import styled from "styled-components"
import {Carousel, Divider, Drawer, Modal, Space, Typography} from "antd"
import {useState} from "react"
import {repeat} from "../util.js"

const Grid = styled.div`
  display: grid;
  grid-template-columns: repeat(3, auto);
  gap: 2px;
  line-height: 0;
`;

const posts = [
    {
        "title": "A marble sculpture of Donald Duck",
        "subtitle": "Generated by the Dall-e Mini Artificial Intelligence 🎨🤖\n\nLink in bio to make your own ✨",
        "hashtags": [
            "#DonaldDuck",
            "#DalleMini",
            "#AI"
        ],
        images: [
            "https://storage.googleapis.com/crazy-dalle/2584a15033ee4cfd9009349317ec8f23.jpg",
            "https://storage.googleapis.com/crazy-dalle/c6478323-bc9e-4767-9b6c-267d2cc714e6.jpg",
            "https://storage.googleapis.com/crazy-dalle/4a8d0040-3d33-4739-9e05-b2c5d1cdf85f.jpg",
            "https://storage.googleapis.com/crazy-dalle/f0eb4ac3-4ea7-4fcb-8802-eb654868037c.jpg",
            "https://storage.googleapis.com/crazy-dalle/055b75ff-61cf-4a34-9b2e-8c9d9e3c91cc.jpg",
            "https://storage.googleapis.com/crazy-dalle/af9f7544-107c-4f23-a122-a915618a404c.jpg",
            "https://storage.googleapis.com/crazy-dalle/5d64c7d6-7fdc-45bf-9cfc-fc399e9bb4ee.jpg",
            "https://storage.googleapis.com/crazy-dalle/5710b738-d9d4-4f50-aacc-85cf8dbc7823.jpg",
            "https://storage.googleapis.com/crazy-dalle/22d14bba-7139-43eb-a5a2-7eda7dc5728a.jpg",
            "https://storage.googleapis.com/crazy-dalle/0dc5bfa3-3b38-41f6-83f6-b4da466fe6cb.jpg"

        ]
    },
    {
        "hashtags": [
            "#KevinBacon",
            "#DalleMini",
            "#AI"
        ],
        "subtitle": "Generated by the Dall-e Mini Artificial Intelligence 🎨🤖\n\nLink in bio to make your own ✨",
        "title": "Kevin Bacon eating a fish",
        images: [
            "https://storage.googleapis.com/crazy-dalle/94d9243992ec437f931075f7464ebf78.jpg",
            "https://storage.googleapis.com/crazy-dalle/bbf09deb-68fc-4f5e-904b-45df4c4a0b75.jpg",
            "https://storage.googleapis.com/crazy-dalle/2c4c47b0-c774-4500-8502-1eb84bc9733d.jpg",
            "https://storage.googleapis.com/crazy-dalle/1e0d3ee3-205c-48e1-aee4-5fdcbe37d76a.jpg",
            "https://storage.googleapis.com/crazy-dalle/4e68f815-d938-41c6-9e27-44b98bec6a8e.jpg",
            "https://storage.googleapis.com/crazy-dalle/6ff687f6-d47b-427c-8dc6-21ea74699e52.jpg",
            "https://storage.googleapis.com/crazy-dalle/acaaaf04-9276-4d61-99fd-e649f8aafcfd.jpg",
            "https://storage.googleapis.com/crazy-dalle/4cabcd14-61af-4048-b2b2-6121b35cef53.jpg",
            "https://storage.googleapis.com/crazy-dalle/478e1452-3ced-459a-9d98-ac985e06883c.jpg",
            "https://storage.googleapis.com/crazy-dalle/dc47f76d-9f05-4798-84c7-8530cbecea6f.jpg"
        ]
    }
]

export default function Home() {
    const [isModalVisible, setModalVisible] = useState(false)
    const [currentPost, setCurrentPost] = useState(null)

    const showModal = post => {
        setCurrentPost(post)
        setModalVisible(true)
    };

    return (
        <>
            <section>
                <Grid>
                    {repeat(posts, 10).map((post, i) => (
                      <div key={i} onClick={() => showModal(post)}>
                          <Image width={780} height={844}
                                 src={post.images[0]} />
                      </div>
                    ))}
                </Grid>
            </section>
            {currentPost !== null && (
              <Drawer visible={isModalVisible}
                     onClose={() => setModalVisible(false)}
                     footer={null}>
                  <div style={{paddingLeft: 10, paddingRight: 10}}>
                      <Carousel>
                          {currentPost.images.map((image, i) => (
                            <Image key={i} width={780}
                                   height={844} src={image} />
                          ))}
                      </Carousel>

                      <Divider />

                      <Space direction={"vertical"}>
                          <Typography.Text>{currentPost.title}</Typography.Text>
                          <Typography.Text>{currentPost.subtitle}</Typography.Text>
                      </Space>

                      <Divider />

                      <Typography.Text>{currentPost.hashtags.join(" ")}</Typography.Text>
                  </div>
              </Drawer>
            )}
        </>
    )
}
